"
A FDExtensionsFilterTest is a test class for testing the behavior of FDExtensionsFilter
"
Class {
	#name : 'StFBExtensionsFilterTest',
	#superclass : 'StFBAbstractFilterTest',
	#category : 'NewTools-FileBrowser-Tests-Filtering',
	#package : 'NewTools-FileBrowser-Tests',
	#tag : 'Filtering'
}

{ #category : 'testing' }
StFBExtensionsFilterTest class >> isAbstract [
	^ self = StFBExtensionsFilterTest
]
