"
Class to hold sample selectors to find.
"
Class {
	#name : 'StFinderMockC',
	#superclass : 'Object',
	#category : 'NewTools-Finder-Tests-Mocks',
	#package : 'NewTools-Finder-Tests',
	#tag : 'Mocks'
}

{ #category : 'accessing' }
StFinderMockC >> aBCSelectorSearchForRegexpStartWithCase [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockC >> abcSelectorSearchForRegexpStartWithoutCase [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockC >> selectorSearchForRegexpWithCaseEndsWithAbc [
	"mock example"
]

{ #category : 'accessing' }
StFinderMockC >> selectorSearchForRegexpWithoutCaseEndsWithabc [
	"mock example"
]
