Class {
	#name : #StDebuggerDummyTestPresenter,
	#superclass : #SpPresenter,
	#category : #'NewTools-Debugger-Tests-Debugger - views'
}

{ #category : #accessing }
StDebuggerDummyTestPresenter class >> debuggerExtensionTestPragma [
	<debuggerExtensionTestPragma>
	
]

{ #category : #accessing }
StDebuggerDummyTestPresenter class >> debuggingExtensionToolName [
	^'Test extendedDebuggingToolTitle'
	
]
