Extension { #name : #EDEmergencyDebugger }

{ #category : #'*Emergency-Debugger-Tests' }
EDEmergencyDebugger >> displayInterface: aDisplayInterface [
	rawDisplay := aDisplayInterface
]

{ #category : #'*Emergency-Debugger-Tests' }
EDEmergencyDebugger >> input [
	^input
]

{ #category : #'*Emergency-Debugger-Tests' }
EDEmergencyDebugger >> methodText [
	^methodText
]

{ #category : #'*Emergency-Debugger-Tests' }
EDEmergencyDebugger >> methodVersionSelectionIndex [
	^methodVersionSelectionIndex
]

{ #category : #'*Emergency-Debugger-Tests' }
EDEmergencyDebugger >> repl: aREPLInterface [
	repl := aREPLInterface
]

{ #category : #'*Emergency-Debugger-Tests' }
EDEmergencyDebugger >> shortStackIndex [
	^shortStackIndex
]

{ #category : #'*Emergency-Debugger-Tests' }
EDEmergencyDebugger >> shortStackIndex: newIndex [
	shortStackIndex := newIndex
]

{ #category : #'*Emergency-Debugger-Tests' }
EDEmergencyDebugger >> stackSelectionIndex [
	^stackSelectionIndex
]

{ #category : #'*Emergency-Debugger-Tests' }
EDEmergencyDebugger >> stackSelectionIndex: newIndex [
	stackSelectionIndex := newIndex
]
