Class {
	#name : 'SindarinSkipAllToSelectionCommand',
	#superclass : 'SindarinCommand',
	#category : 'NewTools-Sindarin-Commands',
	#package : 'NewTools-Sindarin-Commands'
}

{ #category : 'accessing' }
SindarinSkipAllToSelectionCommand class >> debuggerExtensionGroup [
	"Pragma to find the method. This method should build and return a customize command groups for the debugger"

]

{ #category : 'accesing - defaults' }
SindarinSkipAllToSelectionCommand class >> defaultIconName [
	^ #glamorousRightSide
]
