Extension { #name : #StRewriterMatchToolPresenter }

{ #category : #'*NewTools-RewriterTools-Tests' }
StRewriterMatchToolPresenter >> astCode [

	"This accessor should ONLY be called in the tests."

	^ astCode
]

{ #category : #'*NewTools-RewriterTools-Tests' }
StRewriterMatchToolPresenter >> astPattern [

	"This accessor should ONLY be called in the tests."

	^ astPattern
]

{ #category : #'*NewTools-RewriterTools-Tests' }
StRewriterMatchToolPresenter >> bindingsTable [

	"This accessor should ONLY be called in the tests."

	^ bindingsTable
]

{ #category : #'*NewTools-RewriterTools-Tests' }
StRewriterMatchToolPresenter >> codeEditor [

	"This accessor should ONLY be called in the tests."

	^ codeEditor
]

{ #category : #'*NewTools-RewriterTools-Tests' }
StRewriterMatchToolPresenter >> matchesList [

	"This accessor should ONLY be called in the tests. This is for not break encapsulation."

	^ matchesList
]

{ #category : #'*NewTools-RewriterTools-Tests' }
StRewriterMatchToolPresenter >> methodCheckbox [

	"This accessor should ONLY be called in the tests. This is for not break encapsulation."

	^ methodCheckbox
]

{ #category : #'*NewTools-RewriterTools-Tests' }
StRewriterMatchToolPresenter >> ruleEditor [

	"This accessor should ONLY be called in the tests."

	^ ruleEditor
]
