Extension { #name : 'StRewriterScopeSelectorPresenter' }

{ #category : '*NewTools-RewriterTools-Tests' }
StRewriterScopeSelectorPresenter >> classesFilteringListPresenter [

	^ classesListWithFilterPresenter
]

{ #category : '*NewTools-RewriterTools-Tests' }
StRewriterScopeSelectorPresenter >> methodsFilteringListPresenter [

	^ methodsListWithFilterPresenter
]

{ #category : '*NewTools-RewriterTools-Tests' }
StRewriterScopeSelectorPresenter >> packagesFilteringListPresenter [

	^ packagesListWithFilterPresenter
]
